services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    # user: 1000:1000
    ports:
      - "4443:80"
    volumes:
      - /path/to/root:/srv # replace path (with what?)
      - /path/to/file_browser/filebrowser.db:/database.db # replace path
      - /path/to/file_browser/.filebrowser.json:/.filebrowser.json # replace path