services:
  nginx:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /path/to/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro # replace path; Take the file from https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/apache/proxy/uploadsize.conf
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes_from:
      - nginx
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - nginx

volumes:
  certs:
  vhost.d:
  html:
  acme:

networks:
  proxy-tier:
    name: proxy-tier
    driver: bridge
