version: '3'

services:
    homeassistant:
        image: ghcr.io/home-assistant/home-assistant:stable
        container_name: homeassistant
        privileged: true
        restart: unless-stopped
        # environment:
        #     - TZ=Europe/Warsaw
        volumes:
            - /path/to/home-assistant/config:/config # replace path
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        network_mode: host
