# This template is based on this example: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml

services:

  database-test:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  nextcloud:
    restart: always
    image: nextcloud:fpm
    depends_on:
      - database-test
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=database-test


  web-test:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    ports:
      - 8081:80
    volumes:
      - /path/to/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # replace path; Take the file from https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm/web
    volumes_from:
      - nextcloud
    depends_on:
      - nextcloud

volumes:
 nextcloud:
 db:
