# Template for qBittorrent wrapped by Hotio with configured VPN (more here: https://hotio.dev/containers/qbittorrent)

services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "<EXPOSED_PORT_FOR_WEBUI>:8080" # Set port on which you want to expose Web UI
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /path/you/want/store/hotio-torrent:/config  # replace path
      - /path/you/want/store/hotio-torrent:/data # replace path